### ISSUE TITLE
npm i ngx-tree -> empty folder

### ISSUE THREAD

**Issue by istiti** [e-cloud/ngx-tree#1]
it seems this npm can't be installed using `npm i ngx-tree` not your repo ? folder empty.

**Comment by e-cloud** [comment]
It's a pity that `ngx-tree` is preemptive registered by others without further development. So my package is published as `@e-cloud/ngx-tree`.

Sorry for the lack document. I will update it with more detail info soon.

**Comment by istiti** [comment]
@e-cloud  no news here... this project's itneresting coz without mobx, when you think improve to last angular version like change deprecated `ngOutletContext` to `ngTemplateOutletContext` to get it workin with v5 of angular
and make dist build on  npm

**Comment by e-cloud** [comment]
@istiti what do you mean by `ngOutletContext`? There is no usage of them in this package anymore for such a while.

**Comment by istiti** [comment]
@e-cloud apologizes me, you are right ! can you make bundle of this on npm will add it instead angular-tree-component

**Comment by e-cloud** [comment]
in fact, it's already on npm, but it's published under my private scope `@e-cloud/ngx-tree`, and the package is public available.

**Comment by istiti** [comment]
yes but i treid to install it many times, it isn't easy (without readme) 
actualy i install it with `npm i @e-cloud/ngx-tree` and import module like `import { NgxTreeModule } from '@e-cloud/ngx-tree';`
I got a lot errors telling me `lodash-es not found function...` so I installed `npm i lodash-es` then I need change something else, to migrate from angular-tree-component library to yours ? 

because now to initialize I import this in my component `import {TreeComponent} from '@e-cloud/ngx-tree';`
then : 
`@ViewChild(TreeComponent) tree : TreeComponent = null;`

then in a ngOnInit for some reason I want access to : ` this.tree.treeModel.nodes.` but console error telling : 

> error TS2341: Property 'nodes' is private and only accessible within class 'TreeModel'.

then I have in template 
```
<tree-root [nodes]="nodes" #tree>
  <ng-template #treeNodeTemplate let-node="node" let-index="index">
```
but i got this error: 

> Can't bind to 'nodes' since it isn't a known property of 'tree-root'. ...bla bla bla


so @e-cloud  do you have pelase guidline to install and use this library easily? 

thanks

**Comment by istiti** [comment]
up

**Comment by e-cloud** [comment]
I will try it today.

**Comment by e-cloud** [comment]
@istiti I've rewrite the docs and generate the gh-pages. Please have a look and see if it helps.

**Comment by scott-ho** [comment]
close for inactive, feel free to reopen it.

**Comment by e-cloud** [comment]
close for inactive, feel free to reopen it.
